#!/bin/bash

commit_file() {
    local file=$1
    local msg=$2
    if [ -f "$file" ]; then
        echo "Processing $file..."
        git add "$file"
        git commit -m "$msg"
        git push
    fi
}

commit_file "alembic/versions/004_phase7_cognition.py" "Update phase 7 cognition alembic migration"
commit_file "src/agents/capability_nodes.py" "Update capability nodes in agents module"
commit_file "src/agents/world_model_nodes.py" "Refactor world model nodes"
commit_file "src/api/routes/swarm.py" "Update swarm API routes"
commit_file "src/api/routes/vision.py" "Update vision API routes"
commit_file "src/autonomy/__init__.py" "Update autonomy module initialization"
commit_file "src/autonomy/autonomous_runner.py" "Improve autonomous runner"
commit_file "src/autonomy/objective_manager.py" "Enhance objective manager"
commit_file "src/autonomy/progress_tracker.py" "Update progress tracker"
commit_file "src/cli/__init__.py" "Update CLI initialization"
commit_file "src/cli/api_client.py" "Update CLI API client"
commit_file "src/cli/config.py" "Update CLI configuration"
commit_file "src/cli/formatters.py" "Refactor CLI formatters"
commit_file "src/cli/main.py" "Update CLI main entry point"
commit_file "src/cognitive_kernel/cognitive_bus.py" "Improve cognitive bus"
commit_file "src/db/enums.py" "Update database enums"
commit_file "src/db/models.py" "Update database models"
commit_file "src/decision/decision_evaluator.py" "Update decision evaluator"
commit_file "src/decision/decision_memory.py" "Update decision memory"
commit_file "src/decision/goal_optimizer.py" "Refactor goal optimizer"
commit_file "src/decision/option_generator.py" "Update option generator"
commit_file "src/decision/risk_engine.py" "Enhance risk engine"
commit_file "src/mental_models/mental_models.py" "Update mental models"
commit_file "src/monitoring/prometheus.py" "Update Prometheus monitoring configuration"
commit_file "src/multimodal/__init__.py" "Update multimodal initialization"
commit_file "src/multimodal/element_detector.py" "Improve element detector"
commit_file "src/multimodal/screenshot_pipeline.py" "Update screenshot pipeline"
commit_file "src/multimodal/vision_processor.py" "Update vision processor"
commit_file "src/multimodal/visual_interaction.py" "Enhance visual interaction"
commit_file "src/research_programs/program_scheduler.py" "Update program scheduler"
commit_file "src/runtime/__init__.py" "Update runtime initialization"
commit_file "src/runtime/agent_runtime.py" "Refactor agent runtime"
commit_file "src/runtime/execution_loop.py" "Update execution loop"
commit_file "src/runtime/task_runtime.py" "Update task runtime"
commit_file "src/safety/action_validator.py" "Improve action validator"
commit_file "src/safety/permission_manager.py" "Update permission manager"
commit_file "src/safety/sandbox_runner.py" "Enhance sandbox runner"
commit_file "src/swarm/__init__.py" "Update swarm module initialization"
commit_file "src/swarm/director.py" "Update swarm director"
commit_file "src/swarm/load_balancer.py" "Improve load balancer"
commit_file "src/swarm/sub_orchestrator.py" "Update sub orchestrator"
commit_file "src/swarm/swarm_coordinator.py" "Refactor swarm coordinator"
commit_file "src/swarm/task_distributor.py" "Update task distributor"
commit_file "tests/e2e/multimodal/vision_test.py" "Update vision e2e tests"
commit_file "tests/e2e/swarm/swarm_test.py" "Update swarm e2e tests"
commit_file "PROJECT_CHANGE_REPORT.md" "Add project change report"
commit_file "alembic/versions/014_phase17_runtime.py" "Add phase 17 runtime alembic migration"
commit_file "src/autonomy/checkpoint_manager.py" "Add checkpoint manager"
commit_file "src/autonomy/recovery.py" "Add autonomy recovery module"
commit_file "src/autonomy/runtime_metrics.py" "Add runtime metrics module"
commit_file "src/autonomy/runtime_scheduler.py" "Add runtime scheduler module"
commit_file "tests/unit/test_autonomous_runtime.py" "Add unit tests for autonomous runtime"
commit_file "tests/unit/test_phase17_runtime.py" "Add unit tests for phase 17 runtime"

echo "All files committed and pushed!"
