"use client";

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

const discoveries = [
  { id: 'DIS-001', title: 'Novel Sorting Algorithm Variant', domain: 'Computer Science', confidence: 0.94, status: 'Verified', date: '2026-06-10' },
  { id: 'DIS-002', title: 'Emergent Logical Deduction Pattern', domain: 'Logic', confidence: 0.88, status: 'Under Review', date: '2026-06-12' },
  { id: 'DIS-003', title: 'Unconventional Material Synthesis Pathway', domain: 'Chemistry', confidence: 0.76, status: 'Hypothesis', date: '2026-06-13' },
  { id: 'DIS-004', title: 'Optimized Matrix Multiplication Method', domain: 'Mathematics', confidence: 0.99, status: 'Verified', date: '2026-06-14' },
];

export default function DiscoveryList() {
  return (
    <div className="p-8 space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Autonomous Discovery</h1>
        <p className="text-muted-foreground mt-2">Log of novel concepts, algorithms, and hypotheses generated by the model.</p>
      </div>

      <div className="grid gap-6">
        {discoveries.map((disc) => (
          <Card key={disc.id}>
            <CardContent className="p-6 flex items-center justify-between">
              <div className="space-y-1">
                <div className="flex items-center gap-3">
                  <h3 className="font-semibold text-lg">{disc.title}</h3>
                  <Badge variant="outline">{disc.id}</Badge>
                </div>
                <div className="text-sm text-muted-foreground flex items-center gap-4">
                  <span>Domain: {disc.domain}</span>
                  <span>Date: {disc.date}</span>
                  <span>Confidence: {(disc.confidence * 100).toFixed(0)}%</span>
                </div>
              </div>
              <div>
                <Badge variant={
                  disc.status === 'Verified' ? 'default' : 
                  disc.status === 'Under Review' ? 'secondary' : 'destructive'
                }>
                  {disc.status}
                </Badge>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
